"""Core ERA5 processing for daily zonal aggregation"""

import functools
import logging
import multiprocessing
import operator
from functools import cache
from pathlib import Path
from typing import Literal

import xarray as xr
from geoglue import AdministrativeLevel
from geoglue.cds import CdsDataset
from geoglue.resample import resample
from geoglue.util import set_lonlat_attrs, sha256

from ...metrics import (
    register_process,
    zonal_stats_xarray,
)
from ...metrics.worldpop import get_worldpop
from ...paths import get_path
from .list_metrics import (
    ACCUM_METRICS,
    DERIVED_METRICS_SEPARATE_IMPL,
    INSTANT_METRICS,
    METRICS,
    VARIABLE_MAPPINGS,
)
from .util import (
    add_bias_corrected_tp,
    get_dataset_pool,
    pprint_ms,
    relative_humidity,
    specific_humidity,
)

logger = logging.getLogger(__name__)

STATS = ["min", "mean", "max", "sum"]


@cache
def get_resampled_paths_daily(region_name: str, year: int) -> dict[str, Path]:
    return {
        stat: get_path(
            "scratch",
            region_name,
            "era5",
            f"{region_name}-{year}-era5.daily_{stat}.resampled.nc",
        )
        for stat in ["mean", "min", "max", "sum"]
    }


def population_weighted_aggregation_daily(
    metric: str,
    statistic: str,
    region: AdministrativeLevel,
    year: int,
) -> Path:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(processName)s] %(levelname)s %(message)s",
    )
    resampled_paths = get_resampled_paths_daily(region.name, year)
    message = f"zonal stats [{region.name}-{region.admin}, {year}] era5.{metric}.daily_{statistic}"

    logger = logging.getLogger(__name__)
    logger.info(f"START {message}")
    operation = (
        "mean(coverage_weight=area_spherical_km2)"
        if metric not in ACCUM_METRICS
        else "area_weighted_sum"
    )
    variable = VARIABLE_MAPPINGS.get(metric, metric)
    resampled_checksum = sha256(resampled_paths[statistic])
    ds = xr.open_dataset(resampled_paths[statistic])
    provenance = ds.attrs.get("provenance", "")
    da = zonal_stats_xarray(
        f"era5.{metric}.daily_{statistic}",
        ds[variable],
        region,
        operation=operation,
        weights=get_worldpop(region, year, nodata_impute=0),
    )
    # clamp relative_humidity to 100%
    if "relative_humidity" in metric:
        da = da.clip(0, 100)
    outfile = metric_path_daily(region.name, region.admin, year, metric, statistic)
    assert outfile.suffix == ".nc"
    da.attrs["provenance"] = (
        f"zonal_stats.ds={resampled_checksum} {resampled_paths[statistic]}\n{provenance}"
    )
    da.to_netcdf(outfile)
    logger.info(f"  END {message} -> {outfile}")
    return outfile


def collect_variables_to_drop(kind: Literal["instant", "accum"]) -> list[str]:
    "Collect list of variables to drop for a particular variable type"
    ms = INSTANT_METRICS if kind == "instant" else ACCUM_METRICS
    collect = set()
    for m in ms:
        collect.update(METRICS[m].get("depends", []))
    vars_to_drop = sorted(collect - set(METRICS.keys()))
    return [VARIABLE_MAPPINGS.get(v, v) for v in vars_to_drop]


def metric_path_daily(
    region_name: str, admin: int, year: int, metric: str, statistic: str
) -> Path:
    assert statistic in STATS
    # save the data array for daily metrics+stats combination in scratch instead
    return get_path(
        "scratch",
        region_name,
        "era5",
        f"{region_name}-{admin}-{year}-era5.{metric}.daily_{statistic}.nc",
    )


def build_merged_daily_dataset(
    region: AdministrativeLevel,
    year: int,
    metric_stat_combis: dict[str, list[str]],
) -> xr.Dataset:
    """Merge all the daily (metrics, stats) combis into a single Dataset"""
    arrays = []
    for stat, metrics in metric_stat_combis.items():
        for m in metrics:
            path = metric_path_daily(region.name, region.admin, year, m, stat)
            da = xr.open_dataarray(path)
            # rename to match that of core weekly
            if stat in ("min", "max") and not da.name.endswith("24"):
                da = da.rename(da.name + "24")
            arrays.append(da)
    ds = xr.merge(arrays)
    return ds


@register_process("era5.core")
def era5_process_core_daily(
    region: AdministrativeLevel,
    date: str,
    overwrite: bool = True,
    keep_resampled: bool = False,
) -> list[Path]:
    """Processes ERA5 data for a particular year

    Parameters
    ----------
    region : AdministrativeLevel
        Administrative level to process
    date : str
        Year for which to process ERA5 data
    overwrite : bool
        Whether to overwrite existing generated data, default=True
    keep_resampled : bool
        Whether to keep files generated by CDO resample. These can be large files
        due to upsampling of source data. Default is False, and resampled files
        are deleted upon completion of processing.

    Returns
    -------
    List of generated or pre-existing data files in parquet format
    """
    year = int(date)
    logger.info(f"Processing {region.name}-{region.admin}-{year}-era5.core")
    paths = {
        stat: get_path(
            "scratch", region.name, "era5", f"{region.name}-{year}-era5.daily_{stat}.nc"
        )
        for stat in ["mean", "min", "max", "sum"]
    }
    # after cdo resampling
    resampled_paths = get_resampled_paths_daily(region.name, year)

    pool = get_dataset_pool(region)
    ds = pool[year]

    # calculate derived metrics
    ds.instant["q"] = specific_humidity(ds.instant)
    ds.instant["r"] = relative_humidity(ds.instant)
    ds.accum["hb"] = ds.accum.tp + ds.accum.e

    # calculate relative humidity

    ds = CdsDataset(
        instant=ds.instant.drop_vars(collect_variables_to_drop("instant")),
        accum=ds.accum.drop_vars(collect_variables_to_drop("accum")),
    )

    logger.info("Calculating daily statistics (mean, sum)")
    daily_agg = ds.daily()  # mean and sum
    daily_agg.instant.to_netcdf(paths["mean"])

    # Read in possible tp_corrected file here and add to accum dataset
    # If no tp_corrected file is found, add_bias_corrected_tp() returns
    # the daily accumulated dataset unaltered.
    # Note that tp_corrected for a year will require the corresponding files
    # for previous and succeeding years depending on shift_hours
    accum = add_bias_corrected_tp(daily_agg.accum, region.name, year)
    is_bias_corrected: bool = "tp_bc" in accum.variables
    if is_bias_corrected:
        accum["hb_bc"] = accum.tp_bc + accum.e
    set_lonlat_attrs(accum)
    accum.to_netcdf(paths["sum"])

    # read in
    logger.info("Calculating daily statistics (min, max)")
    ds.daily_max().to_netcdf(paths["max"])
    ds.daily_min().to_netcdf(paths["min"])

    instant_metrics = [
        m for m in INSTANT_METRICS if m not in (DERIVED_METRICS_SEPARATE_IMPL + ["core_weekly"])
    ]
    accum_metrics = [m for m in ACCUM_METRICS if m not in (DERIVED_METRICS_SEPARATE_IMPL + ["core_weekly"]) ]
    if not is_bias_corrected:
        instant_metrics = [m for m in instant_metrics if not m.endswith("_corrected")]
        accum_metrics = [m for m in accum_metrics if not m.endswith("_corrected")]

    metric_statistic_combinations: dict[str, list[str]] = {
        s: instant_metrics for s in ["min", "max", "mean"]
    }
    metric_statistic_combinations.update({"sum": accum_metrics})

    # check number of metrics already existed 
    already_existing_metrics: dict[str, list[str]] = {
        s: [
            m
            for m in metric_statistic_combinations[s]
            if metric_path_daily(region.name, region.admin, year, m, s).exists()
        ]
        for s in metric_statistic_combinations
    }
    n_already_existing_metrics: int = sum(
        len(already_existing_metrics[s]) for s in already_existing_metrics
    )

    # get (metrics, stats) combinations to be computed
    generated_paths = []
    if not overwrite and n_already_existing_metrics:
        generated_paths = functools.reduce(
            operator.iadd,
            [
                [
                    metric_path_daily(region.name, region.admin, year, m, s)
                    for m in already_existing_metrics[s]
                ]
                for s in already_existing_metrics
            ],
            [],
        )
        logger.info(
            "Metric statistic combinations: %s",
            pprint_ms(metric_statistic_combinations, already_existing_metrics),
        )
        # filter to keep only metrics that need to be calculated
        to_compute_metric_statistic = {
            s: [
                m
                for m in metric_statistic_combinations[s]
                if m not in already_existing_metrics[s]
            ]
            for s in metric_statistic_combinations
        }
    else:
        logger.info(
            "Metric statistic combinations: %s",
            pprint_ms(metric_statistic_combinations),
        )
        to_compute_metric_statistic = metric_statistic_combinations

    # compute metric + statistic combinations that haven't been computed b4 
    for stat in to_compute_metric_statistic:
        # skip if no metrics are requested to be generated for statistic
        metrics = to_compute_metric_statistic[stat]
        if not metrics:
            continue
        logger.info("Computing zonal aggregation for statistic=%s", stat)
        resampling = "remapdis" if stat == "sum" else "remapbil"
        logger.info(
            f"Resampling using CDO for {stat=} using {resampling=}: {paths[stat]} -> {resampled_paths[stat]}"
        )
        resample(
            resampling,
            paths[stat],
            get_worldpop(region, year, nodata_impute=0),
            resampled_paths[stat],
        )
        with multiprocessing.Pool() as p:
            new_paths = list(
                p.map(
                    functools.partial(
                        # note that this func already renamed
                        population_weighted_aggregation_daily,
                        statistic=stat,
                        region=region,
                        year=year,
                    ),
                    metrics,
                )
            )
        if not keep_resampled:
            resampled_paths[stat].unlink()
        generated_paths += new_paths

    # Generate a core_daily dataset for current (region, year) dataset
    ds = build_merged_daily_dataset(region, year, metric_statistic_combinations)
    ds.attrs = {
        "DART_population": str(get_worldpop(region, year)),
        "DART_region": f"{region.name} {region.pk} {region.tz}",
    }
        
    # returned value is the Dataset with all the core_variables instead
    return ds
    # return generated_paths