"""
Load dataset

Params:
    Dataset (string) : Dataset to load; options are:
        'APHRODITE Daily mean temperature product (V1808)'
        'APHRODITE Daily accumulated precipitation (V1901)'
        'CHIRPS: Rainfall Estimates from Rain Gauge and Satellite Observations'
        'TerraClimate gridded temperature, precipitation, and other'
        'ERA5 atmospheric reanalysis'
        'WorldPop population density'
        'WorldPop population count'
        'GADM administrative map'
    Admin Level: "1"
    Year: ""
    Resolution Type:
        "ppp" : people per pixel
        "pph" : people per hectare
    Country (iso3): "VNM"
    Options (string) : Additional command line arguments to pass.
"""
configfile: "config/config.yaml"
from snakemake.remote import AUTO
params = config["params"]

rule target:
    input:
        script = AUTO.remote(srcdir("../resources/scripts/process_data.py")),
    output:
        directory(
            expand(
                "results/{outdir}",
                outdir=config["output_namespace"],
            )
        )
    params:
        dataset = params["Dataset"],
        base_dir = config["input_namespace"],
        opts = params["Options"],
        admin_level = params["Admin Level"],
        year = params["Year"],
        resolution_type = params["Resolution Type"],
        country_iso3 = params["Country (ISO3)"],
    conda:
        "envs/conda.yaml"
    shell:
        """
        python3 {input.script} \
            --data_name="{params.dataset}" \
            --base_directory={params.base_dir} \
            --admin_level={params.admin_level} \
            --year={params.year} \
            --resolution_type={params.resolution_type} \
            --country_iso3={params.country_iso3} \
            {params.opts}
        """
