services:

  db:
    image: postgis/postgis:16-3.4
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ../data/db:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3

  models_model1:
    build:
      context: ..
      dockerfile: models/model1/Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "app.py"]

  climate:
    build:
      context: ..
      dockerfile: ingestion/climate/Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "app.py"]

  epi:
    build:
      context: ..
      dockerfile: ingestion/epi/Dockerfile
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "app.py"]
