# Resampling is bilinear (remapbil) when sum daily statistic is not present
# is remapdis otherwise, can be overriden with resampling key

[sources.chirps]
description = "Climate Hazards Group InfraRed Precipitation with Station"
license_text = """To the extent possible under the law, Pete Peterson
has waived all copyright and related or neighboring rights to CHIRPS.
CHIRPS data is in the public domain as registered with Creative Commons.
This work is published from: the United States."""
url = "https://www.chc.ucsb.edu/data/chirps"
attribution = ""

[sources.era5]
description = "ERA5 reanalysis data"
license_text = """Access to Copernicus Products is given for any purpose in so far
as it is lawful, whereas use may include, but is not limited to: reproduction;
distribution; communication to the public; adaptation, modification and
combination with other data and information; or any combination of the
foregoing."""
url = [
  "https://cds.climate.copernicus.eu/datasets/derived-era5-single-levels-daily-statistics",
  "https://cds.climate.copernicus.eu/datasets/reanalysis-era5-single-levels?tab=overview"
]
auth = true
auth_url = "https://cds.climate.copernicus.eu/how-to-api"
attribution = ""
resolution = "0.25 degree"
years = [1940, "now"]
accum_vars = ["evaporation", "total_precipitation", "surface_solar_radiation_downwards"]

[sources.era5.variable_mappings]
2m_temperature = "t2m"
surface_solar_radiation_downwards = "ssrd"
2m_dewpoint_temperature = "d2m"
surface_pressure = "sp"
evaporation = "e"
total_precipitation = "tp"
10m_u_component_of_wind = "u10"
10m_v_component_of_wind = "v10"


[sources.meta]
description = "Meta Data for Good"
url = "https://dataforgood.facebook.com/"

[sources.gadm]
description = "GADM administrative areas"
license_text = """The data are freely available for academic use and other
non-commercial use. Redistribution or commercial use is not allowed
without prior permission."""
license_url = "https://gadm.org/license.html"
url = "https://gadm.org"
redistribution_allowed = false

[sources.ecmwf_forecast]
description = "ECMWF forecast data"
license_text = "..."
license_url = "..."
redistribution_allowed = false

[sources.worldpop]
description = "WorldPop population data"
license = "CC-BY-4.0"
url = "https://worldpop.org"
attribution = ""
resolution = "1 km"

[chirps.rainfall]
description = "CHIRPS rainfall estimates from rain gauge, satellite observations"
units = "??"
statistics = ["daily_sum"]

[era5.2m_temperature]
description = "2 meters air temperature"
units = "degree_Celsius"
resampling = "remapbil"
range = [-50, 50]

[era5.surface_solar_radiation_downwards]
description = "Accumulated solar radiation downwards"
units = "J/m^2"
range = [0, 1e9]
resampling = "remapbil"

[era5.total_precipitation]
description = "Total precipitation"
units = "m"
range = [0, 1200]

[era5.wind_speed]
description = "Wind speed"
depends = ["10m_u_component_of_wind", "10m_v_component_of_wind"]
units = "m/s"
range = [0, 110]
range_citation = "https://en.wikipedia.org/wiki/Wind_speed%23Non-tornadic"

[era5.relative_humidity]
description = "Relative humidity"
depends = ["2m_temperature", "2m_dewpoint_temperature", "surface_pressure"]
units = "percentage"
range = [0, 100]

[era5.specific_humidity]
description = "Specific humidity"
depends = ["2m_temperature", "2m_dewpoint_temperature", "surface_pressure"]
units = "g/kg"
range = [0, 30]

[era5.hydrological_balance]
description = "Hydrological balance"
units = "m"
depends = ["evaporation", "total_precipitation"]

[era5.spi]
description = "Standardised precipitation index"
depends = ["total_precipitation"]
units = "unitless"

[era5.spie]
description = "Standardised precipitation-evaporation index"
# actually depends on potential_evapotranspiration which depends
# on 2m_temperature.{daily_min,daily_mean,daily_max}
depends = ["total_precipitation", "2m_temperature"]
units = "unitless"

[era5.bc_total_precipitation]
description = "Bias-corrected total precipitation"
depends = ["total_precipitation"]
units = "m"

[era5.bc_spi]
description = "Bias-corrected standardised precipitation index"
depends = ["total_precipitation"]
units = "unitless"

[era5.bc_spie]
description = "Bias-corrected standardised precipitation-evaporation index"
# actually depends on potential_evapotranspiration which depends
# on 2m_temperature.{daily_min,daily_mean,daily_max}
depends = ["total_precipitation", "2m_temperature"]
units = "unitless"

[era5.bc_hydrological_balance]
description = "Bias-corrected hydrological balance"
depends = ["evaporation", "total_precipitation"]
units = "m"

[meta.relative_wealth_index]
description = "Relative wealth index"
units = "unitless"
statistics = ["mean"]
license = "CC-BY-4.0"
url = "https://data.humdata.org/dataset/relative-wealth-index"

[worldpop.population_count]
description = "Population count, unconstrained, UN adjusted"
units = "unitless"
statistics = ["sum"]
url = "https://hub.worldpop.org/geodata/listing?id=75"
years = [2000, 2020]

[worldpop.population_density]
description = "Population density, unconstrained, UN adjusted"
units = "km^{-2}"
statistics = ["mean"]
url = "https://hub.worldpop.org/geodata/listing?id=77"
years = [2000, 2020]
