"""
Load dataset

Params:
    Dataset (string) : Dataset to load; options are:
        'APHRODITE Daily mean temperature product (V1808)'
        'APHRODITE Daily accumulated precipitation (V1901)'
        'CHIRPS: Rainfall Estimates from Rain Gauge and Satellite Observations'
        'TerraClimate gridded temperature, precipitation, and other'
        'ERA5 atmospheric reanalysis'
        'WorldPop population density'
        'WorldPop population count'
        'GADM administrative map'
    Options (string) : Additional command line arguments to pass. These include:
        --only_one : Only one item from each folder will be downloaded
        --dry_run : Empty files will be created in lieu of downloaded data
"""
configfile: "config/config.yaml"
from snakemake.remote import AUTO
params = config["params"]

rule target:
    input:
        login = expand(
            "results/{indir}/{creds}",
            indir=config["input_namespace"]["login"],
            creds=params["Credentials file"],
        ),
        script = AUTO.remote(srcdir("../resources/scripts/collate_data.py")),
    output:
        directory(
            expand(
                "results/{outdir}",
                outdir=config["output_namespace"],
            )
        )
    params:
        dataset = params["Dataset"],
        opts = params["Options"],
    conda:
        "envs/conda.yaml"
    shell:
        """
        mkdir -p {output}
        python3 {input.script} \
            --data_name="{params.dataset}" \
            --output_directory="{output}" \
            --cred="{input.login}"
            {params.opts}
        """
