name: docker

# Avoid building on every code change, only on changes to dependencies
# (pyproject.toml and uv.lock), the Dockerfile and CI changes
on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/docker.yml
      - Dockerfile
      - build_docker.sh
      - pyproject.toml
      - uv.lock
  pull_request:
    branches: [ "main" ]
    paths:
      - .github/workflows/docker.yml
      - Dockerfile
      - build_docker.sh
      - pyproject.toml
      - uv.lock
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Build docker image
      run: ./build_docker.sh
