name: scripts

on:
  push:
    paths:
      - '.github/workflows/scripts.yml'
      - 'scripts/**'
  pull_request:
    paths:
      - '.github/workflows/scripts.yml'
      - 'scripts/**'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck on scripts/
        run: shellcheck scripts/*
